/* See LICENSE file for license and copyright information */

#ifndef LIBFLUSH_EVICTION_CONFIGURATION_H
#define LIBFLUSH_EVICTION_CONFIGURATION_H

#define ADDRESS_CACHE_SIZE 128

#define USE_FIXED_MEMORY_SIZE 1
#define PHYSICAL_MEMORY_MAPPED_SIZE (10 * 1024 * 1024)
#define FRACTION_OF_PHYSICAL_MEMORY 0.1

#endif // LIBFLUSH_EVICTION_CONFIGURATION_H
